### ISSUE TITLE
Try Raymarching

### ISSUE THREAD

**Issue by sirboblos** [8dcc/raycasting#1]
Hello Good Sir :D
long time no see huh
try ray marching too, it's fun :D

**Comment by 8dcc** [comment]
Very interesting, never heard of it. I am not sure if it will be useful for this project since I wanted to use the raycasting for a simple simulation like Wolfenstein 1:

![image](https://github.com/8dcc/raycasting/assets/29655971/18a5b4f3-4627-42cf-b41a-a9ebdcf3a7c0)
